package lestharkin.app.view;

import java.text.SimpleDateFormat;
import java.util.Iterator;

import lestharkin.domain.Appointment;
import lestharkin.interfaces.ILinkedList;
import lestharkin.interfaces.ILinkedListNode;

/**
 *
 * @author lesth
 */
public class AppointmentJFrame extends javax.swing.JFrame {

  private ILinkedList<Appointment> list;

  /**
   * Creates new form AppointmentJFrame
   */
  public AppointmentJFrame(ILinkedList<Appointment> list) {
    this.list = list;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jScrollPane2 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jMenuBar = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItemNew = new javax.swing.JMenuItem();
    jMenuItemExit = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Appointment");
    setPreferredSize(new java.awt.Dimension(800, 600));

    Iterator<ILinkedListNode<Appointment>> i = list.iterator();
    String[] title = new String[] {
        "ID", "Cliente", "Fecha", "Descripción", "Estado"
    };
    Object[][] object = new Object[this.list.size()][title.length];

    int j = 0;

    while (i.hasNext()) {
      Appointment appointment = i.next().getObject();
      object[j][0] = appointment.getId();
      object[j][1] = appointment.getCustomer().getNames() + " " + appointment.getCustomer().getLastNames();
      object[j][2] = new SimpleDateFormat("yyyy-MM-dd").format(appointment.getDate());
      object[j][3] = appointment.getDescription();
      object[j][4] = appointment.isClosed();
      j++;
    }

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        object,
        title));
    jScrollPane2.setViewportView(jTable1);

    jMenu1.setText("File");

    jMenuItemNew.setAccelerator(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItemNew.setText("Nuevo");
    jMenuItemNew.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemNewActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItemNew);

    jMenuItemExit.setAccelerator(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItemExit.setText("Salir");
    jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemExitActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItemExit);

    jMenuBar.add(jMenu1);

    setJMenuBar(jMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap()));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap()));

    pack();
  }// </editor-fold>

  private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {
    System.exit(0);
  }

  private void jMenuItemNewActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AppointmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AppointmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AppointmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AppointmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    }
    // </editor-fold>

    
  }

  // Variables declaration - do not modify
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar;
  private javax.swing.JMenuItem jMenuItemExit;
  private javax.swing.JMenuItem jMenuItemNew;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1;
  // End of variables declaration
}
